package com.chen.dao.mapper;

import com.chen.entity.WXUserConcact;

public interface WXUserConcactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_concact
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_concact
     *
     * @mbg.generated
     */
    int insert(WXUserConcact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_concact
     *
     * @mbg.generated
     */
    int insertSelective(WXUserConcact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_concact
     *
     * @mbg.generated
     */
    WXUserConcact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_concact
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WXUserConcact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user_concact
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WXUserConcact record);

    WXUserConcact getByUnionIdAndNickName(WXUserConcact wxUserConcact);
}