package com.chen.dao.mapper;

import com.chen.entity.WXUser;
import com.chen.model.WXUserModel;

public interface WXUserMapper {

    WXUser getUserByUin(String uid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    int insert(WXUser record);

    int insertByModel(WXUserModel wxUserModel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    int insertSelective(WXUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    WXUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WXUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WXUser record);
}