package com.chen.entity;

public class WXUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.uin
     *
     * @mbg.generated
     */
    private String uin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.userName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.nickName
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.headImgUrl
     *
     * @mbg.generated
     */
    private String headImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.contactFlag
     *
     * @mbg.generated
     */
    private String contactFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.memberCount
     *
     * @mbg.generated
     */
    private String memberCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.remarkName
     *
     * @mbg.generated
     */
    private String remarkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.hideInputBarFlag
     *
     * @mbg.generated
     */
    private String hideInputBarFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.signature
     *
     * @mbg.generated
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.verifyFlag
     *
     * @mbg.generated
     */
    private String verifyFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.ownerUin
     *
     * @mbg.generated
     */
    private String ownerUin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.pYInitial
     *
     * @mbg.generated
     */
    private String pYInitial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.remarkPYQuanPin
     *
     * @mbg.generated
     */
    private String remarkPYQuanPin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.pYQuanPin
     *
     * @mbg.generated
     */
    private String pYQuanPin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.remarkPYInitial
     *
     * @mbg.generated
     */
    private String remarkPYInitial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.starFriend
     *
     * @mbg.generated
     */
    private String starFriend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.appAccountFlag
     *
     * @mbg.generated
     */
    private String appAccountFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.statues
     *
     * @mbg.generated
     */
    private String statues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.attrStatus
     *
     * @mbg.generated
     */
    private String attrStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.alias
     *
     * @mbg.generated
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.snsFlag
     *
     * @mbg.generated
     */
    private String snsFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.uniFriend
     *
     * @mbg.generated
     */
    private String uniFriend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.displayName
     *
     * @mbg.generated
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.chatRoomId
     *
     * @mbg.generated
     */
    private String chatRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.keyWord
     *
     * @mbg.generated
     */
    private String keyWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.encryChatRoomId
     *
     * @mbg.generated
     */
    private String encryChatRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.isOwner
     *
     * @mbg.generated
     */
    private String isOwner;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.id
     *
     * @return the value of wx_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.id
     *
     * @param id the value for wx_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.uin
     *
     * @return the value of wx_user.uin
     *
     * @mbg.generated
     */
    public String getUin() {
        return uin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.uin
     *
     * @param uin the value for wx_user.uin
     *
     * @mbg.generated
     */
    public void setUin(String uin) {
        this.uin = uin == null ? null : uin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.userName
     *
     * @return the value of wx_user.userName
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.userName
     *
     * @param userName the value for wx_user.userName
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.nickName
     *
     * @return the value of wx_user.nickName
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.nickName
     *
     * @param nickName the value for wx_user.nickName
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.headImgUrl
     *
     * @return the value of wx_user.headImgUrl
     *
     * @mbg.generated
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.headImgUrl
     *
     * @param headImgUrl the value for wx_user.headImgUrl
     *
     * @mbg.generated
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.contactFlag
     *
     * @return the value of wx_user.contactFlag
     *
     * @mbg.generated
     */
    public String getContactFlag() {
        return contactFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.contactFlag
     *
     * @param contactFlag the value for wx_user.contactFlag
     *
     * @mbg.generated
     */
    public void setContactFlag(String contactFlag) {
        this.contactFlag = contactFlag == null ? null : contactFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.memberCount
     *
     * @return the value of wx_user.memberCount
     *
     * @mbg.generated
     */
    public String getMemberCount() {
        return memberCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.memberCount
     *
     * @param memberCount the value for wx_user.memberCount
     *
     * @mbg.generated
     */
    public void setMemberCount(String memberCount) {
        this.memberCount = memberCount == null ? null : memberCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.remarkName
     *
     * @return the value of wx_user.remarkName
     *
     * @mbg.generated
     */
    public String getRemarkName() {
        return remarkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.remarkName
     *
     * @param remarkName the value for wx_user.remarkName
     *
     * @mbg.generated
     */
    public void setRemarkName(String remarkName) {
        this.remarkName = remarkName == null ? null : remarkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.hideInputBarFlag
     *
     * @return the value of wx_user.hideInputBarFlag
     *
     * @mbg.generated
     */
    public String getHideInputBarFlag() {
        return hideInputBarFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.hideInputBarFlag
     *
     * @param hideInputBarFlag the value for wx_user.hideInputBarFlag
     *
     * @mbg.generated
     */
    public void setHideInputBarFlag(String hideInputBarFlag) {
        this.hideInputBarFlag = hideInputBarFlag == null ? null : hideInputBarFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.sex
     *
     * @return the value of wx_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.sex
     *
     * @param sex the value for wx_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.signature
     *
     * @return the value of wx_user.signature
     *
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.signature
     *
     * @param signature the value for wx_user.signature
     *
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.verifyFlag
     *
     * @return the value of wx_user.verifyFlag
     *
     * @mbg.generated
     */
    public String getVerifyFlag() {
        return verifyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.verifyFlag
     *
     * @param verifyFlag the value for wx_user.verifyFlag
     *
     * @mbg.generated
     */
    public void setVerifyFlag(String verifyFlag) {
        this.verifyFlag = verifyFlag == null ? null : verifyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.ownerUin
     *
     * @return the value of wx_user.ownerUin
     *
     * @mbg.generated
     */
    public String getOwnerUin() {
        return ownerUin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.ownerUin
     *
     * @param ownerUin the value for wx_user.ownerUin
     *
     * @mbg.generated
     */
    public void setOwnerUin(String ownerUin) {
        this.ownerUin = ownerUin == null ? null : ownerUin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.pYInitial
     *
     * @return the value of wx_user.pYInitial
     *
     * @mbg.generated
     */
    public String getpYInitial() {
        return pYInitial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.pYInitial
     *
     * @param pYInitial the value for wx_user.pYInitial
     *
     * @mbg.generated
     */
    public void setpYInitial(String pYInitial) {
        this.pYInitial = pYInitial == null ? null : pYInitial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.remarkPYQuanPin
     *
     * @return the value of wx_user.remarkPYQuanPin
     *
     * @mbg.generated
     */
    public String getRemarkPYQuanPin() {
        return remarkPYQuanPin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.remarkPYQuanPin
     *
     * @param remarkPYQuanPin the value for wx_user.remarkPYQuanPin
     *
     * @mbg.generated
     */
    public void setRemarkPYQuanPin(String remarkPYQuanPin) {
        this.remarkPYQuanPin = remarkPYQuanPin == null ? null : remarkPYQuanPin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.pYQuanPin
     *
     * @return the value of wx_user.pYQuanPin
     *
     * @mbg.generated
     */
    public String getpYQuanPin() {
        return pYQuanPin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.pYQuanPin
     *
     * @param pYQuanPin the value for wx_user.pYQuanPin
     *
     * @mbg.generated
     */
    public void setpYQuanPin(String pYQuanPin) {
        this.pYQuanPin = pYQuanPin == null ? null : pYQuanPin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.remarkPYInitial
     *
     * @return the value of wx_user.remarkPYInitial
     *
     * @mbg.generated
     */
    public String getRemarkPYInitial() {
        return remarkPYInitial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.remarkPYInitial
     *
     * @param remarkPYInitial the value for wx_user.remarkPYInitial
     *
     * @mbg.generated
     */
    public void setRemarkPYInitial(String remarkPYInitial) {
        this.remarkPYInitial = remarkPYInitial == null ? null : remarkPYInitial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.starFriend
     *
     * @return the value of wx_user.starFriend
     *
     * @mbg.generated
     */
    public String getStarFriend() {
        return starFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.starFriend
     *
     * @param starFriend the value for wx_user.starFriend
     *
     * @mbg.generated
     */
    public void setStarFriend(String starFriend) {
        this.starFriend = starFriend == null ? null : starFriend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.appAccountFlag
     *
     * @return the value of wx_user.appAccountFlag
     *
     * @mbg.generated
     */
    public String getAppAccountFlag() {
        return appAccountFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.appAccountFlag
     *
     * @param appAccountFlag the value for wx_user.appAccountFlag
     *
     * @mbg.generated
     */
    public void setAppAccountFlag(String appAccountFlag) {
        this.appAccountFlag = appAccountFlag == null ? null : appAccountFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.statues
     *
     * @return the value of wx_user.statues
     *
     * @mbg.generated
     */
    public String getStatues() {
        return statues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.statues
     *
     * @param statues the value for wx_user.statues
     *
     * @mbg.generated
     */
    public void setStatues(String statues) {
        this.statues = statues == null ? null : statues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.attrStatus
     *
     * @return the value of wx_user.attrStatus
     *
     * @mbg.generated
     */
    public String getAttrStatus() {
        return attrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.attrStatus
     *
     * @param attrStatus the value for wx_user.attrStatus
     *
     * @mbg.generated
     */
    public void setAttrStatus(String attrStatus) {
        this.attrStatus = attrStatus == null ? null : attrStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.province
     *
     * @return the value of wx_user.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.province
     *
     * @param province the value for wx_user.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.city
     *
     * @return the value of wx_user.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.city
     *
     * @param city the value for wx_user.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.alias
     *
     * @return the value of wx_user.alias
     *
     * @mbg.generated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.alias
     *
     * @param alias the value for wx_user.alias
     *
     * @mbg.generated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.snsFlag
     *
     * @return the value of wx_user.snsFlag
     *
     * @mbg.generated
     */
    public String getSnsFlag() {
        return snsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.snsFlag
     *
     * @param snsFlag the value for wx_user.snsFlag
     *
     * @mbg.generated
     */
    public void setSnsFlag(String snsFlag) {
        this.snsFlag = snsFlag == null ? null : snsFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.uniFriend
     *
     * @return the value of wx_user.uniFriend
     *
     * @mbg.generated
     */
    public String getUniFriend() {
        return uniFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.uniFriend
     *
     * @param uniFriend the value for wx_user.uniFriend
     *
     * @mbg.generated
     */
    public void setUniFriend(String uniFriend) {
        this.uniFriend = uniFriend == null ? null : uniFriend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.displayName
     *
     * @return the value of wx_user.displayName
     *
     * @mbg.generated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.displayName
     *
     * @param displayName the value for wx_user.displayName
     *
     * @mbg.generated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.chatRoomId
     *
     * @return the value of wx_user.chatRoomId
     *
     * @mbg.generated
     */
    public String getChatRoomId() {
        return chatRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.chatRoomId
     *
     * @param chatRoomId the value for wx_user.chatRoomId
     *
     * @mbg.generated
     */
    public void setChatRoomId(String chatRoomId) {
        this.chatRoomId = chatRoomId == null ? null : chatRoomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.keyWord
     *
     * @return the value of wx_user.keyWord
     *
     * @mbg.generated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.keyWord
     *
     * @param keyWord the value for wx_user.keyWord
     *
     * @mbg.generated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord == null ? null : keyWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.encryChatRoomId
     *
     * @return the value of wx_user.encryChatRoomId
     *
     * @mbg.generated
     */
    public String getEncryChatRoomId() {
        return encryChatRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.encryChatRoomId
     *
     * @param encryChatRoomId the value for wx_user.encryChatRoomId
     *
     * @mbg.generated
     */
    public void setEncryChatRoomId(String encryChatRoomId) {
        this.encryChatRoomId = encryChatRoomId == null ? null : encryChatRoomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.isOwner
     *
     * @return the value of wx_user.isOwner
     *
     * @mbg.generated
     */
    public String getIsOwner() {
        return isOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.isOwner
     *
     * @param isOwner the value for wx_user.isOwner
     *
     * @mbg.generated
     */
    public void setIsOwner(String isOwner) {
        this.isOwner = isOwner == null ? null : isOwner.trim();
    }
}